SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `article` (
  `id` int(11) NOT NULL,
  `title` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_at` datetime DEFAULT NULL,
  `image_file` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `article` (`id`, `title`, `content`, `published_at`, `image_file`) VALUES
(NULL, '1. Lorem ipsum dolor', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos esse dicta, minima neque, aspernatur odio deserunt quasi amet quis blanditiis dolores, perspiciatis soluta? Sed placeat rem ab sequi sunt quas nam mollitia blanditiis deserunt, delectus obcaecati vitae consequatur laudantium excepturi dolore voluptatem nihil iusto in iste numquam repellendus perferendis qui aliquid nesciunt. Rerum excepturi facilis ullam! Tenetur nesciunt quidem est ab optio sit ipsam tempora deserunt magnam id, iste eum repudiandae dignissimos reprehenderit unde quas sed. Harum quia ad fuga pariatur, dolorem beatae iste quisquam doloribus nisi dignissimos a fugiat voluptas non facere necessitatibus rem, libero deserunt amet incidunt perspiciatis, consequuntur nesciunt soluta. Exercitationem ut aspernatur minus blanditiis consectetur maiores ipsam. Numquam, repudiandae aliquid adipisci facilis eligendi iure odio maxime accusantium a, blanditiis tempora quae magnam nulla sequi illo fuga quis officiis exercitationem labore excepturi eum sit quisquam illum veritatis! Nostrum aliquam debitis accusamus exercitationem, deserunt cum sapiente omnis ex architecto vel quasi facilis dignissimos totam in perspiciatis expedita! Facilis accusamus porro laboriosam dicta voluptatem. Temporibus hic doloribus dignissimos similique et, repellat corrupti?', '2022-04-01 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '2. Quasi quisquam explicabo', 'Quasi quisquam explicabo expedita molestiae. Quia officia, enim quod cupiditate perferendis ullam. Ipsam est autem blanditiis qui praesentium error modi placeat. Minus odit hic in? Temporibus nostrum sint tempora saepe! Quis doloribus delectus eaque quos libero commodi et consectetur voluptatibus animi sit iure ut ipsam adipisci harum sequi nobis corrupti temporibus, perspiciatis saepe nesciunt nam! Quia saepe minus inventore dignissimos quas unde porro tenetur similique asperiores distinctio excepturi beatae earum voluptates optio quibusdam et dicta culpa ut eius modi, nemo eligendi laborum. Animi illum delectus dignissimos aut cum nobis tempore deserunt mollitia modi repellendus velit eligendi molestias aliquam, natus quaerat neque accusantium. Laboriosam quidem modi autem odio eligendi nisi non explicabo obcaecati nihil, ullam minima voluptatem accusantium adipisci reprehenderit! Ab consequuntur blanditiis quo vitae voluptatum nulla veritatis reiciendis pariatur laboriosam voluptates assumenda voluptas dolorum ipsa similique ipsam odit, dolor, velit qui. Commodi soluta expedita sint velit sit porro id beatae fugiat accusamus eum? Expedita blanditiis commodi harum aliquid modi nostrum rerum magnam animi laboriosam debitis autem, corporis delectus officiis ipsa possimus dicta sapiente, asperiores inventore doloremque.', '2022-04-02 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '3. Suscipit expedita fuga repellendus', 'Suscipit expedita fuga repellendus soluta mollitia cupiditate fugiat culpa consequuntur inventore optio quo, vel maxime qui corrupti cumque? Et quidem necessitatibus dolore cum, ea minus sed? Vero cum iusto, quibusdam saepe obcaecati et quas. Ratione dolor cumque facere vero impedit. Ipsum, vel. Id, possimus molestias aliquid sunt distinctio deserunt atque necessitatibus a rem nam commodi doloremque saepe accusantium repudiandae eum expedita dignissimos, aperiam fugit iste quos blanditiis? Sed corporis neque soluta quod, nesciunt nisi cupiditate esse praesentium sequi molestias commodi enim qui excepturi atque adipisci repellat deserunt et dolore possimus sunt officiis ipsum! Quaerat explicabo voluptatibus ipsam, a possimus, harum debitis quo tempora fuga maxime commodi tempore. Ipsa autem ratione delectus minima fugit vero labore numquam distinctio neque facilis! Eius, aut? Consequatur mollitia quam praesentium deleniti fugit et ad nulla cum vero esse quas quaerat quis sunt perspiciatis, dolorem laudantium iusto animi necessitatibus quibusdam explicabo placeat voluptate illum. Deleniti quas voluptatem laborum asperiores libero tempora optio soluta voluptatum at reprehenderit. Quasi placeat natus, earum voluptate reiciendis asperiores tempore mollitia nisi quo ab architecto!', '2022-04-03 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '4. Quaerat tenetur ex itaque eligendi', 'Quaerat tenetur ex itaque eligendi perspiciatis velit quidem praesentium voluptatum, laboriosam asperiores molestiae optio commodi quos modi odio. Omnis dolores magnam nisi distinctio quas exercitationem sint sequi, assumenda asperiores a incidunt corrupti corporis laudantium similique hic quisquam recusandae atque autem rem, maxime sunt eos. Officia cumque totam possimus nesciunt saepe debitis officiis eum at ducimus sapiente rem excepturi nobis, ab quam reprehenderit ea quo, et maiores. Nam quod necessitatibus temporibus blanditiis facilis. Tenetur, quibusdam autem corporis quidem ipsam repellendus! Alias magni quisquam sed, repellat ducimus deserunt qui repudiandae expedita praesentium temporibus! Consectetur aperiam itaque, saepe earum ut ipsa alias adipisci rerum totam, quia odio culpa laudantium tempore iure voluptates assumenda veritatis quaerat tenetur minima dolorem dolores illum beatae quis. Magnam eveniet cumque doloremque provident nemo praesentium nostrum esse doloribus ea a tenetur reprehenderit recusandae et quos quasi quia, maiores voluptatum illum! Nam nulla aliquid ut aspernatur autem sunt enim aut, earum porro aliquam voluptate illo sint recusandae corporis error impedit officia ipsam culpa explicabo.', '2022-04-04 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '5. Aperiam quod excepturi', 'Aperiam quod excepturi, cupiditate omnis, dolorum dolores placeat eum illo voluptas, recusandae iure voluptates temporibus non. Labore id voluptates nesciunt. Cupiditate minima maiores quia doloremque itaque, possimus quae fugit magnam exercitationem necessitatibus dolor eaque, nihil ducimus? Doloremque officia quidem reprehenderit incidunt velit corporis. Incidunt omnis aspernatur enim odit minima deleniti, nobis sequi asperiores facilis repudiandae est temporibus maiores dicta optio libero iure debitis quas facere nemo. Assumenda iste nesciunt voluptas odit. Doloremque aperiam, eos dolores, dolore magnam debitis fugiat provident error sequi quam, fugit nam earum praesentium in necessitatibus hic quo. Mollitia earum, doloribus, delectus ducimus sunt beatae accusantium iste cumque, exercitationem quos adipisci minus nihil velit quaerat dolorem eos dolores reiciendis amet! Iusto voluptates cumque cupiditate repellat ab quaerat possimus accusantium sit dolorem voluptas quisquam, magnam ad totam impedit beatae repellendus recusandae nostrum rem neque corporis. Assumenda quasi quisquam magni dicta iure, laboriosam pariatur dolor nobis animi, eius suscipit maiores temporibus odio! Dolor vitae maiores asperiores alias possimus qui veritatis minus ratione officia!', '2022-04-05 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '6. Architecto, a nesciunt voluptates', 'Architecto, a nesciunt voluptates possimus facilis quae ab sed reprehenderit vitae laboriosam cum eos, maiores veritatis excepturi pariatur inventore quaerat ullam temporibus suscipit iusto nobis iste. Atque sit quasi recusandae natus praesentium repellat in odit sint. Necessitatibus temporibus optio sunt ipsum pariatur aut! Debitis eaque aliquam voluptatibus, temporibus, eligendi accusantium quia pariatur ex qui similique facere, exercitationem quasi! Debitis, dignissimos. Dicta qui libero aliquid, illo mollitia quisquam eaque ex, eius nam ipsam nisi cumque ratione pariatur repellat voluptate iste ut omnis cum totam possimus est sunt. Eius sunt quaerat consequatur labore, hic non ab deleniti architecto qui earum magnam quasi libero amet voluptatum error dignissimos rem, maiores harum fuga? Quis dolorem, provident eius iure ab atque ipsam ex ut porro commodi quasi dolores inventore minima cumque odit autem ipsa, minus tempora mollitia repudiandae eligendi a quas? Nesciunt, fugiat assumenda! Harum laboriosam dolorum tenetur doloribus nisi aut reiciendis labore facilis consectetur repellendus delectus, sint error odit ratione optio officiis ipsa fuga! Ad eos voluptatum ullam accusamus perspiciatis ipsam voluptas.', '2022-04-06 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '7. Nisi est magnam maxime et, cupiditate', 'Nisi est magnam maxime et, cupiditate tempora odio modi, optio minima molestias nihil necessitatibus aperiam mollitia, voluptatem accusantium omnis explicabo fugit sed reprehenderit tempore! Incidunt magni facere dolorem fuga totam, ullam dicta doloribus. Incidunt in sit qui deserunt sapiente quos dolorum minima. Natus quod architecto nesciunt dolore, odio minima quam omnis corporis nemo eligendi vitae est sequi! Debitis placeat esse pariatur sint dicta nihil omnis? At hic unde accusantium, dolorem, adipisci ullam earum atque blanditiis quasi, esse saepe accusamus eveniet! Aliquid libero accusantium temporibus voluptatum labore vel, suscipit omnis dolorum impedit eos tempore repudiandae nisi, quo ipsam nemo expedita maxime? Sunt in nesciunt, nulla quae ullam cumque hic eveniet deleniti, est sit iure doloremque sed ex distinctio perspiciatis commodi, eos assumenda consectetur ea temporibus odio quod. Atque eos at nobis adipisci vero repellat odio asperiores repudiandae rerum voluptates, assumenda, corrupti molestias nesciunt aliquid recusandae quaerat officiis consectetur enim praesentium magnam culpa sint! Nihil accusantium consequuntur porro accusamus deserunt quaerat veritatis expedita similique error soluta, assumenda explicabo!', '2022-04-07 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '8. Nisi voluptate corrupti mollitia', 'Nisi voluptate corrupti mollitia minus facere aspernatur. Doloribus beatae eaque error ullam natus eum iure tempore. Temporibus fuga eos at consectetur incidunt, veniam facilis officiis voluptate corrupti nihil quam omnis vero, earum aperiam assumenda exercitationem reprehenderit odio cumque eligendi a, culpa ut quis. Vitae iste asperiores cupiditate maiores nulla nemo omnis officiis neque, vero facere reiciendis explicabo reprehenderit dolor sint vel voluptatibus distinctio nostrum sequi aspernatur nam at iure rerum tempora. Nemo totam facilis eveniet sed atque nihil nulla quisquam tempore ipsam eius, esse quas a, perspiciatis ut perferendis architecto fugit repellat ad! Est porro vitae rerum laudantium ipsam provident quisquam reiciendis magnam modi tenetur cum dignissimos, suscipit, magni aut mollitia! Ut ullam impedit explicabo voluptatem ex quasi quae harum velit. Doloremque ut, quaerat perspiciatis, commodi neque dolor voluptas ipsa corrupti suscipit aut est ipsam consequuntur omnis, distinctio iusto. Totam explicabo illo, obcaecati inventore veniam ipsam! At culpa hic voluptas possimus quos minus architecto id eos officia iusto facilis mollitia odit nemo, repudiandae accusamus inventore itaque recusandae quaerat pariatur laudantium nesciunt.', '2022-04-08 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '9. Lorem ipsum dolor', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos esse dicta, minima neque, aspernatur odio deserunt quasi amet quis blanditiis dolores, perspiciatis soluta? Sed placeat rem ab sequi sunt quas nam mollitia blanditiis deserunt, delectus obcaecati vitae consequatur laudantium excepturi dolore voluptatem nihil iusto in iste numquam repellendus perferendis qui aliquid nesciunt. Rerum excepturi facilis ullam! Tenetur nesciunt quidem est ab optio sit ipsam tempora deserunt magnam id, iste eum repudiandae dignissimos reprehenderit unde quas sed. Harum quia ad fuga pariatur, dolorem beatae iste quisquam doloribus nisi dignissimos a fugiat voluptas non facere necessitatibus rem, libero deserunt amet incidunt perspiciatis, consequuntur nesciunt soluta. Exercitationem ut aspernatur minus blanditiis consectetur maiores ipsam. Numquam, repudiandae aliquid adipisci facilis eligendi iure odio maxime accusantium a, blanditiis tempora quae magnam nulla sequi illo fuga quis officiis exercitationem labore excepturi eum sit quisquam illum veritatis! Nostrum aliquam debitis accusamus exercitationem, deserunt cum sapiente omnis ex architecto vel quasi facilis dignissimos totam in perspiciatis expedita! Facilis accusamus porro laboriosam dicta voluptatem. Temporibus hic doloribus dignissimos similique et, repellat corrupti?', '2022-04-09 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '10. Quasi quisquam explicabo', 'Quasi quisquam explicabo expedita molestiae. Quia officia, enim quod cupiditate perferendis ullam. Ipsam est autem blanditiis qui praesentium error modi placeat. Minus odit hic in? Temporibus nostrum sint tempora saepe! Quis doloribus delectus eaque quos libero commodi et consectetur voluptatibus animi sit iure ut ipsam adipisci harum sequi nobis corrupti temporibus, perspiciatis saepe nesciunt nam! Quia saepe minus inventore dignissimos quas unde porro tenetur similique asperiores distinctio excepturi beatae earum voluptates optio quibusdam et dicta culpa ut eius modi, nemo eligendi laborum. Animi illum delectus dignissimos aut cum nobis tempore deserunt mollitia modi repellendus velit eligendi molestias aliquam, natus quaerat neque accusantium. Laboriosam quidem modi autem odio eligendi nisi non explicabo obcaecati nihil, ullam minima voluptatem accusantium adipisci reprehenderit! Ab consequuntur blanditiis quo vitae voluptatum nulla veritatis reiciendis pariatur laboriosam voluptates assumenda voluptas dolorum ipsa similique ipsam odit, dolor, velit qui. Commodi soluta expedita sint velit sit porro id beatae fugiat accusamus eum? Expedita blanditiis commodi harum aliquid modi nostrum rerum magnam animi laboriosam debitis autem, corporis delectus officiis ipsa possimus dicta sapiente, asperiores inventore doloremque.', '2022-04-10 12:40:12.000000', 'screen-tester.jpg'),
(NULL, '11. Suscipit expedita fuga repellendus', 'Suscipit expedita fuga repellendus soluta mollitia cupiditate fugiat culpa consequuntur inventore optio quo, vel maxime qui corrupti cumque? Et quidem necessitatibus dolore cum, ea minus sed? Vero cum iusto, quibusdam saepe obcaecati et quas. Ratione dolor cumque facere vero impedit. Ipsum, vel. Id, possimus molestias aliquid sunt distinctio deserunt atque necessitatibus a rem nam commodi doloremque saepe accusantium repudiandae eum expedita dignissimos, aperiam fugit iste quos blanditiis? Sed corporis neque soluta quod, nesciunt nisi cupiditate esse praesentium sequi molestias commodi enim qui excepturi atque adipisci repellat deserunt et dolore possimus sunt officiis ipsum! Quaerat explicabo voluptatibus ipsam, a possimus, harum debitis quo tempora fuga maxime commodi tempore. Ipsa autem ratione delectus minima fugit vero labore numquam distinctio neque facilis! Eius, aut? Consequatur mollitia quam praesentium deleniti fugit et ad nulla cum vero esse quas quaerat quis sunt perspiciatis, dolorem laudantium iusto animi necessitatibus quibusdam explicabo placeat voluptate illum. Deleniti quas voluptatem laborum asperiores libero tempora optio soluta voluptatum at reprehenderit. Quasi placeat natus, earum voluptate reiciendis asperiores tempore mollitia nisi quo ab architecto!', '2022-04-11 12:40:12.000000', 'screen-tester.jpg');

CREATE TABLE `article_category` (
  `article_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `article_category` (`article_id`, `category_id`) VALUES
(1, 1),
(2, 2);

CREATE TABLE `category` (
  `id` int(11) NOT NULL,
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `category` (`id`, `name`) VALUES
(4, 'climate'),
(1, 'news'),
(2, 'sports'),
(3, 'tech');

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `user` (`id`, `username`, `password`) VALUES
(1, 'niko', '$2y$10$e0aSdO8e8CnnMuiTOmYz/umfMbJHmrj5acieyAiq6QUD3EfWDzm/S');


ALTER TABLE `article`
  ADD PRIMARY KEY (`id`),
  ADD KEY `title` (`title`);

ALTER TABLE `article_category`
  ADD PRIMARY KEY (`article_id`,`category_id`),
  ADD KEY `category_id` (`category_id`);

ALTER TABLE `category`
  ADD PRIMARY KEY (`id`),
  ADD KEY `name` (`name`);

ALTER TABLE `user`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);


ALTER TABLE `article`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `article_category`
  ADD CONSTRAINT `article_category_ibfk_1` FOREIGN KEY (`article_id`) REFERENCES `article` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `article_category_ibfk_2` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
